#!/bin/sh

# Create a lib directory in the virtual file system for a tclkit app
# and copy some files into it.
#
# usage: vfslib app package packagefile*
#    copy the files into the package directory
# usage: vfslib app
#    clear out the old and create a new package directory

APP=$1 ; shift
ROOT=`pwd`/kit/$APP.vfs

if test $# -eq 0; then
    rm -rf $ROOT
    install -d $ROOT
else
    PACKAGE=$1 ; shift

    install -d $ROOT/lib/$PACKAGE
    cp -p $* $ROOT/lib/$PACKAGE
fi
